register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: POST
api:
    path: /apii
    controller: App\Controller\AuthController::api
login_check:
    path:     /login_check
    methods: [POST]
users:
    type: rest
    resource: App\Controller\UsersController